# DO NOT EDIT THIS FILE!
#
# Python module LeaderboardService__POA generated by omniidl

import omniORB
omniORB.updateModule("LeaderboardService__POA")

# ** 1. Stub files contributing to this module
from finProject.corba import LeaderboardService_idl

# ** 2. Sub-modules

# ** 3. End
