package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, April 9, 2025 7:31:42 AM SGT
*/

public interface HelloOperations 
{
  String sayHello (String name);
} // interface HelloOperations
