package PalindromeApp;


/**
* PalindromeApp/PalindromePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Palindrome.idl
* Wednesday, April 9, 2025 4:38:31 PM SGT
*/

public abstract class PalindromePOA extends org.omg.PortableServer.Servant
 implements PalindromeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("isPalindrome", new Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PalindromeApp/Palindrome/isPalindrome
       {
         String value = in.read_string ();
         boolean $result = false;
         $result = this.isPalindrome (value);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PalindromeApp/Palindrome:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Palindrome _this() 
  {
    return PalindromeHelper.narrow(
    super._this_object());
  }

  public Palindrome _this(org.omg.CORBA.ORB orb) 
  {
    return PalindromeHelper.narrow(
    super._this_object(orb));
  }


} // class PalindromePOA
