package PalindromeApp;


/**
* PalindromeApp/PalindromeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Palindrome.idl
* Wednesday, April 9, 2025 4:38:31 PM SGT
*/

public interface PalindromeOperations 
{
  boolean isPalindrome (String value);
} // interface PalindromeOperations
