package PalindromeApp;

/**
* PalindromeApp/PalindromeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Palindrome.idl
* Wednesday, April 9, 2025 4:38:31 PM SGT
*/

public final class PalindromeHolder implements org.omg.CORBA.portable.Streamable
{
  public Palindrome value = null;

  public PalindromeHolder ()
  {
  }

  public PalindromeHolder (Palindrome initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PalindromeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PalindromeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PalindromeHelper.type ();
  }

}
