# DO NOT EDIT THIS FILE!
#
# Python module LoginService__POA generated by omniidl

import omniORB
omniORB.updateModule("LoginService__POA")

# ** 1. Stub files contributing to this module
from finProject.corba import LoginService_idl

# ** 2. Sub-modules

# ** 3. End
