package HangmanApp;

/**
* HangmanApp/HangmanGameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Monday, April 14, 2025 4:33:11 AM SGT
*/

public final class HangmanGameHolder implements org.omg.CORBA.portable.Streamable
{
  public HangmanGame value = null;

  public HangmanGameHolder ()
  {
  }

  public HangmanGameHolder (HangmanGame initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HangmanGameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HangmanGameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HangmanGameHelper.type ();
  }

}
