package HangmanApp;


/**
* HangmanApp/HangmanGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Monday, April 14, 2025 4:33:11 AM SGT
*/

public interface HangmanGame extends HangmanGameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HangmanGame
