package HangmanApp;


/**
* HangmanApp/HangmanGameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Monday, April 14, 2025 4:33:11 AM SGT
*/

abstract public class HangmanGameHelper
{
  private static String  _id = "IDL:HangmanApp/HangmanGame:1.0";

  public static void insert (org.omg.CORBA.Any a, HangmanGame that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HangmanGame extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HangmanGameHelper.id (), "HangmanGame");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HangmanGame read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HangmanGameStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HangmanGame value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HangmanGame narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HangmanGame)
      return (HangmanGame)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _HangmanGameStub stub = new _HangmanGameStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HangmanGame unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HangmanGame)
      return (HangmanGame)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _HangmanGameStub stub = new _HangmanGameStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
