package HangmanApp;


/**
* HangmanApp/HangmanGameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Monday, April 14, 2025 4:33:11 AM SGT
*/

public interface HangmanGameOperations 
{
  String guessLetter (String letter);
  String getWordProgress ();
  boolean isGameOver ();
  boolean isWin ();
} // interface HangmanGameOperations
