# DO NOT EDIT THIS FILE!
#
# Python module GuessWordService__POA generated by omniidl

import omniORB
omniORB.updateModule("GuessWordService__POA")

# ** 1. Stub files contributing to this module
from finProject.corba import GuessWordService_idl

# ** 2. Sub-modules

# ** 3. End
