# DO NOT EDIT THIS FILE!
#
# Python module HeartbeatService__POA generated by omniidl

import omniORB
omniORB.updateModule("HeartbeatService__POA")

# ** 1. Stub files contributing to this module
from finProject.corba import HeartbeatService_idl

# ** 2. Sub-modules

# ** 3. End
