# DO NOT EDIT THIS FILE!
#
# Python module StartGameService generated by omniidl

import omniORB
omniORB.updateModule("StartGameService")

# ** 1. Stub files contributing to this module
from finProject.corba import StartGameService_idl

# ** 2. Sub-modules

# ** 3. End
