# Python stubs generated by omniidl from GuessWordService.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "GuessWordService"
#
__name__ = "GuessWordService"
_0_GuessWordService = omniORB.openModule("GuessWordService", r"GuessWordService.idl")
_0_GuessWordService__POA = omniORB.openModule("GuessWordService__POA", r"GuessWordService.idl")


# interface GuessWord
_0_GuessWordService._d_GuessWord = (omniORB.tcInternal.tv_objref, "IDL:GuessWordService/GuessWord:1.0", "GuessWord")
omniORB.typeMapping["IDL:GuessWordService/GuessWord:1.0"] = _0_GuessWordService._d_GuessWord
_0_GuessWordService.GuessWord = omniORB.newEmptyClass()
class GuessWord :
    _NP_RepositoryId = _0_GuessWordService._d_GuessWord[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_GuessWordService.GuessWord = GuessWord
_0_GuessWordService._tc_GuessWord = omniORB.tcInternal.createTypeCode(_0_GuessWordService._d_GuessWord)
omniORB.registerType(GuessWord._NP_RepositoryId, _0_GuessWordService._d_GuessWord, _0_GuessWordService._tc_GuessWord)

# GuessWord operations and attributes
GuessWord._d_checkInput = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
GuessWord._d_getWords = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
GuessWord._d_time_configuration = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
GuessWord._d_startGame = (((omniORB.tcInternal.tv_string,0), ), (), None)
GuessWord._d_isWinner = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
GuessWord._d_resetRound = ((omniORB.tcInternal.tv_long, ), (), None)
GuessWord._d_getWinner = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
GuessWord._d_setWinner = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), None)
GuessWord._d_finalWinner = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
GuessWord._d_setGameDone = ((omniORB.tcInternal.tv_long, ), (), None)
GuessWord._d_nextGameTime = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
GuessWord._d_get_players = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)

# GuessWord object reference
class _objref_GuessWord (CORBA.Object):
    _NP_RepositoryId = GuessWord._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def checkInput(self, *args):
        return self._obj.invoke("checkInput", _0_GuessWordService.GuessWord._d_checkInput, args)

    def getWords(self, *args):
        return self._obj.invoke("getWords", _0_GuessWordService.GuessWord._d_getWords, args)

    def time_configuration(self, *args):
        return self._obj.invoke("time_configuration", _0_GuessWordService.GuessWord._d_time_configuration, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_GuessWordService.GuessWord._d_startGame, args)

    def isWinner(self, *args):
        return self._obj.invoke("isWinner", _0_GuessWordService.GuessWord._d_isWinner, args)

    def resetRound(self, *args):
        return self._obj.invoke("resetRound", _0_GuessWordService.GuessWord._d_resetRound, args)

    def getWinner(self, *args):
        return self._obj.invoke("getWinner", _0_GuessWordService.GuessWord._d_getWinner, args)

    def setWinner(self, *args):
        return self._obj.invoke("setWinner", _0_GuessWordService.GuessWord._d_setWinner, args)

    def finalWinner(self, *args):
        return self._obj.invoke("finalWinner", _0_GuessWordService.GuessWord._d_finalWinner, args)

    def setGameDone(self, *args):
        return self._obj.invoke("setGameDone", _0_GuessWordService.GuessWord._d_setGameDone, args)

    def nextGameTime(self, *args):
        return self._obj.invoke("nextGameTime", _0_GuessWordService.GuessWord._d_nextGameTime, args)

    def get_players(self, *args):
        return self._obj.invoke("get_players", _0_GuessWordService.GuessWord._d_get_players, args)

omniORB.registerObjref(GuessWord._NP_RepositoryId, _objref_GuessWord)
_0_GuessWordService._objref_GuessWord = _objref_GuessWord
del GuessWord, _objref_GuessWord

# GuessWord skeleton
__name__ = "GuessWordService__POA"
class GuessWord (PortableServer.Servant):
    _NP_RepositoryId = _0_GuessWordService.GuessWord._NP_RepositoryId


    _omni_op_d = {"checkInput": _0_GuessWordService.GuessWord._d_checkInput, "getWords": _0_GuessWordService.GuessWord._d_getWords, "time_configuration": _0_GuessWordService.GuessWord._d_time_configuration, "startGame": _0_GuessWordService.GuessWord._d_startGame, "isWinner": _0_GuessWordService.GuessWord._d_isWinner, "resetRound": _0_GuessWordService.GuessWord._d_resetRound, "getWinner": _0_GuessWordService.GuessWord._d_getWinner, "setWinner": _0_GuessWordService.GuessWord._d_setWinner, "finalWinner": _0_GuessWordService.GuessWord._d_finalWinner, "setGameDone": _0_GuessWordService.GuessWord._d_setGameDone, "nextGameTime": _0_GuessWordService.GuessWord._d_nextGameTime, "get_players": _0_GuessWordService.GuessWord._d_get_players}

GuessWord._omni_skeleton = GuessWord
_0_GuessWordService__POA.GuessWord = GuessWord
omniORB.registerSkeleton(GuessWord._NP_RepositoryId, GuessWord)
__name__ = "GuessWordService"

#
# End of module "GuessWordService"
#
__name__ = "GuessWordService_idl"

_exported_modules = ( "GuessWordService", )

# The end.
