# Python stubs generated by omniidl from HeartbeatService.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "HeartbeatService"
#
__name__ = "HeartbeatService"
_0_HeartbeatService = omniORB.openModule("HeartbeatService", r"HeartbeatService.idl")
_0_HeartbeatService__POA = omniORB.openModule("HeartbeatService__POA", r"HeartbeatService.idl")


# interface Heartbeat
_0_HeartbeatService._d_Heartbeat = (omniORB.tcInternal.tv_objref, "IDL:HeartbeatService/Heartbeat:1.0", "Heartbeat")
omniORB.typeMapping["IDL:HeartbeatService/Heartbeat:1.0"] = _0_HeartbeatService._d_Heartbeat
_0_HeartbeatService.Heartbeat = omniORB.newEmptyClass()
class Heartbeat :
    _NP_RepositoryId = _0_HeartbeatService._d_Heartbeat[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_HeartbeatService.Heartbeat = Heartbeat
_0_HeartbeatService._tc_Heartbeat = omniORB.tcInternal.createTypeCode(_0_HeartbeatService._d_Heartbeat)
omniORB.registerType(Heartbeat._NP_RepositoryId, _0_HeartbeatService._d_Heartbeat, _0_HeartbeatService._tc_Heartbeat)

# Heartbeat operations and attributes
Heartbeat._d_ping = ((), (), None)

# Heartbeat object reference
class _objref_Heartbeat (CORBA.Object):
    _NP_RepositoryId = Heartbeat._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def ping(self, *args):
        return self._obj.invoke("ping", _0_HeartbeatService.Heartbeat._d_ping, args)

omniORB.registerObjref(Heartbeat._NP_RepositoryId, _objref_Heartbeat)
_0_HeartbeatService._objref_Heartbeat = _objref_Heartbeat
del Heartbeat, _objref_Heartbeat

# Heartbeat skeleton
__name__ = "HeartbeatService__POA"
class Heartbeat (PortableServer.Servant):
    _NP_RepositoryId = _0_HeartbeatService.Heartbeat._NP_RepositoryId


    _omni_op_d = {"ping": _0_HeartbeatService.Heartbeat._d_ping}

Heartbeat._omni_skeleton = Heartbeat
_0_HeartbeatService__POA.Heartbeat = Heartbeat
omniORB.registerSkeleton(Heartbeat._NP_RepositoryId, Heartbeat)
__name__ = "HeartbeatService"

#
# End of module "HeartbeatService"
#
__name__ = "HeartbeatService_idl"

_exported_modules = ( "HeartbeatService", )

# The end.
