# Python stubs generated by omniidl from LeaderboardService.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "LeaderboardService"
#
__name__ = "LeaderboardService"
_0_LeaderboardService = omniORB.openModule("LeaderboardService", r"LeaderboardService.idl")
_0_LeaderboardService__POA = omniORB.openModule("LeaderboardService__POA", r"LeaderboardService.idl")


# struct StatEntry
_0_LeaderboardService.StatEntry = omniORB.newEmptyClass()
class StatEntry (omniORB.StructBase):
    _NP_RepositoryId = "IDL:LeaderboardService/StatEntry:1.0"

    def __init__(self, username, value):
        self.username = username
        self.value = value

_0_LeaderboardService.StatEntry = StatEntry
_0_LeaderboardService._d_StatEntry  = (omniORB.tcInternal.tv_struct, StatEntry, StatEntry._NP_RepositoryId, "StatEntry", "username", (omniORB.tcInternal.tv_string,0), "value", omniORB.tcInternal.tv_long)
_0_LeaderboardService._tc_StatEntry = omniORB.tcInternal.createTypeCode(_0_LeaderboardService._d_StatEntry)
omniORB.registerType(StatEntry._NP_RepositoryId, _0_LeaderboardService._d_StatEntry, _0_LeaderboardService._tc_StatEntry)
del StatEntry

# typedef ... StatEntryList
class StatEntryList:
    _NP_RepositoryId = "IDL:LeaderboardService/StatEntryList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_LeaderboardService.StatEntryList = StatEntryList
_0_LeaderboardService._d_StatEntryList  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:LeaderboardService/StatEntry:1.0"], 0)
_0_LeaderboardService._ad_StatEntryList = (omniORB.tcInternal.tv_alias, StatEntryList._NP_RepositoryId, "StatEntryList", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:LeaderboardService/StatEntry:1.0"], 0))
_0_LeaderboardService._tc_StatEntryList = omniORB.tcInternal.createTypeCode(_0_LeaderboardService._ad_StatEntryList)
omniORB.registerType(StatEntryList._NP_RepositoryId, _0_LeaderboardService._ad_StatEntryList, _0_LeaderboardService._tc_StatEntryList)
del StatEntryList

# interface Leaderboard
_0_LeaderboardService._d_Leaderboard = (omniORB.tcInternal.tv_objref, "IDL:LeaderboardService/Leaderboard:1.0", "Leaderboard")
omniORB.typeMapping["IDL:LeaderboardService/Leaderboard:1.0"] = _0_LeaderboardService._d_Leaderboard
_0_LeaderboardService.Leaderboard = omniORB.newEmptyClass()
class Leaderboard :
    _NP_RepositoryId = _0_LeaderboardService._d_Leaderboard[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_LeaderboardService.Leaderboard = Leaderboard
_0_LeaderboardService._tc_Leaderboard = omniORB.tcInternal.createTypeCode(_0_LeaderboardService._d_Leaderboard)
omniORB.registerType(Leaderboard._NP_RepositoryId, _0_LeaderboardService._d_Leaderboard, _0_LeaderboardService._tc_Leaderboard)

# Leaderboard operations and attributes
Leaderboard._d_setRoundWinner = (((omniORB.tcInternal.tv_string,0), ), (), None)
Leaderboard._d_setGameWinner = (((omniORB.tcInternal.tv_string,0), ), (), None)
Leaderboard._d_getWinners = ((), (omniORB.typeMapping["IDL:LeaderboardService/StatEntryList:1.0"], ), None)
Leaderboard._d_getPlaces = ((), (omniORB.typeMapping["IDL:LeaderboardService/StatEntryList:1.0"], ), None)

# Leaderboard object reference
class _objref_Leaderboard (CORBA.Object):
    _NP_RepositoryId = Leaderboard._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def setRoundWinner(self, *args):
        return self._obj.invoke("setRoundWinner", _0_LeaderboardService.Leaderboard._d_setRoundWinner, args)

    def setGameWinner(self, *args):
        return self._obj.invoke("setGameWinner", _0_LeaderboardService.Leaderboard._d_setGameWinner, args)

    def getWinners(self, *args):
        return self._obj.invoke("getWinners", _0_LeaderboardService.Leaderboard._d_getWinners, args)

    def getPlaces(self, *args):
        return self._obj.invoke("getPlaces", _0_LeaderboardService.Leaderboard._d_getPlaces, args)

omniORB.registerObjref(Leaderboard._NP_RepositoryId, _objref_Leaderboard)
_0_LeaderboardService._objref_Leaderboard = _objref_Leaderboard
del Leaderboard, _objref_Leaderboard

# Leaderboard skeleton
__name__ = "LeaderboardService__POA"
class Leaderboard (PortableServer.Servant):
    _NP_RepositoryId = _0_LeaderboardService.Leaderboard._NP_RepositoryId


    _omni_op_d = {"setRoundWinner": _0_LeaderboardService.Leaderboard._d_setRoundWinner, "setGameWinner": _0_LeaderboardService.Leaderboard._d_setGameWinner, "getWinners": _0_LeaderboardService.Leaderboard._d_getWinners, "getPlaces": _0_LeaderboardService.Leaderboard._d_getPlaces}

Leaderboard._omni_skeleton = Leaderboard
_0_LeaderboardService__POA.Leaderboard = Leaderboard
omniORB.registerSkeleton(Leaderboard._NP_RepositoryId, Leaderboard)
__name__ = "LeaderboardService"

#
# End of module "LeaderboardService"
#
__name__ = "LeaderboardService_idl"

_exported_modules = ( "LeaderboardService", )

# The end.
